<table class="hint-table">
	<tr class="hint-header" 
		id="idRobotsTxtHintHeader"
		title="Click to open this section"
		onclick="toggleBody(this, window.document.getElementById('idRobotsTxtHintBody'), window.document.getElementById('idRobotsTxtHintHeaderImage'));"
		onmouseover="this.style.backgroundColor='#cccccc';this.style.color='#ffffff';"
		onmouseout="this.style.backgroundColor='#FFFFFF';this.style.color='#000000';"
	>
		<td><img id="idRobotsTxtHintHeaderImage" align="left" style="padding-right: 5px;" alt="Expand Robots.txt Hints" src="./images/down_arrow_16_16.png" />
			Robots.txt Hints
		</td>
	</tr>
	<tr id="idRobotsTxtHintBody" style="display: none;">
		<td class="hint-body">
			<br/><br/>
			<span class="report-header">Overview</span>
			<br/><br/>
			The Robot Exclusion Standard, Robots Exclusion Protocol or robots.txt protocol is a 
			suggestion for "honest" browsers which should prevent web crawlers 
			from accessing the parts of a website listed in the roboos.txt file.
			<br/><br/>
			<span class="report-header">Discovery Methodology</span>
			<br/><br/>
			Browse to the robots.txt file in Mutillidae
			<br/><br/>
			<span class="report-header">Exploitation</span>
			<br/><br/>
			Follow the paths in the robots.txt file
			<br/><br/>
			<span class="report-header">Example</span>
			<br/><br/>
			Robots.txt is located at localhost/mutillidae/robots.txt
			<br/><br/>
		</td>
	</tr>
</table>