			<br/><br/>
			<span class="report-header">Overview</span>
			<br/><br/>
			The Robot Exclusion Standard, Robots Exclusion Protocol or robots.txt protocol is a 
			suggestion for "honest" browsers which should prevent web crawlers 
			from accessing the parts of a website listed in the roboos.txt file.
			<br/><br/>
			<span class="report-header">Discovery Methodology</span>
			<br/><br/>
			Browse to the robots.txt file in Mutillidae
			<br/><br/>
			<span class="report-header">Exploitation</span>
			<br/><br/>
			Follow the paths in the robots.txt file
			<br/><br/>
			<span class="report-header">Example</span>
			<br/><br/>
			Robots.txt is located at localhost/mutillidae/robots.txt
			<br/><br/>