<?php
	/*
	 * @author: Jeremy Druin
	 */
?>

<div>&nbsp;</div>
<table class="tutorial">
	<tr class="tutorial-title">
		<td colspan="10">Insufficient Transport Layer Protection Tutorial</td>
	</tr>
	<tr>
		<td>
			<br/>
			Use a packet sniffer such as TCPDump or Wireshark to observe traffic. Information
			such as the users password should be encrypted as it goes across the wire.
			<br/><br/> 
		</td>
	</tr>
</table>